### ISSUE TITLE
This is amazing, I believe this is the right direction. I’m eager to see when the guru will post more of this smart solution.

### ISSUE THREAD

**Issue by GithungDang** [ysymyth/awesome-language-agents#3]

**Comment by GithungDang** [comment]
I wonder if I will be fortunate enough to see the code for the implementation of the framework mentioned in the paper uploaded to GitHub.

**Comment by lucas-acc** [comment]
Agree, really impressive work.

**Comment by ysymyth** [comment]
thanks! look out for our future works for implementations :)
